[build]
  publish = "docs/.vitepress/dist"
  command = "npm run build"

[context.production]
  [context.production.environment]
    NODE_ENV = "production"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[dev]
  framework = "vitepress"